### PR TITLE
 car servicing station

### PR DESCRIPTION
**Pull request by DEEP411**

### CODE REVIEW

**Comment by DEEP411** [comment]
hi

**Comment by ArmaanTheSharma** [comment]
hello

**Comment by ArmaanTheSharma** [comment]
chat here

**Comment by DEEP411** [comment]
We can code by using vs code

**Comment by DEEP411** [comment]
And we can use any language over there to code like Java, python, c,c++,etc

**Comment by ArmaanTheSharma** [comment]
It's better to NOT use vs studio, since ultimately we have to run the code on IDLE Python only. So we should use github for coding and execute in default IDLE Python itself.

**Comment by DEEP411** [comment]
How ,

**Comment by DEEP411** [comment]
I don't know how to do that in github , to use python as default to code?

**Comment by ArmaanTheSharma** [comment]
I meant to use the regular app IDLE, like we do in computer labs, not on github.

**Comment by DEEP411** [comment]
Ok we will do code individually and send the idle file to check whether the code is correct or not

**Comment by DEEP411** [comment]
Send your profile to lalit sir and told them to join this pull request

**Comment by DEEP411** [comment]
now how can I edit this code ?

**Pull request closed without merging**
